config/routes.rb
PhotoArchive::Application.routes.draw do
  scope module: :web do
    root to: "welcome#index"
    resource :users, only: [:new, :create] 
    resource :sessions, only: [:new, :create, :destroy]
    resource :albums, only: [:show, :index]
    namespace :admin do 
      root to: "welcome#index"
      resources :albums, except: :show 
      resources :images, except: :show 
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :image, presence: true
  validates :album_id, presence: true
  belongs_to :album
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation  
  validates :email, presence: true
  validates :password, presence: true, on: :create
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/web/admin/albums_controller.rb
class Web::Admin::AlbumsController < Web::Admin::ApplicationController
  def index
    @web_admin_albums = Album.all
  end

  def show
    @web_admin_album = Album.find(params[:id])
  end

  def new
    @web_admin_album = Album.new
  end

  def edit
    @web_admin_album = Album.find(params[:id])
  end

  def create
    @web_admin_album = Album.new(params[:album])
    if @web_admin_album.save
      redirect_to admin_albums_path, notice: 'Album was successfully created.'
    else
      render action: "new" 
    end
  end

  def update
    @web_admin_album = Album.find(params[:id])

    if @web_admin_album.update_attributes(params[:album])
      redirect_to admin_albums_path, notice: 'Album was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @web_admin_album = Album.find(params[:id])
    @web_admin_album.destroy
    redirect_to admin_albums_url 
  end
end

app/controllers/web/admin/application_controller.rb
class Web::Admin::ApplicationController < Web::ApplicationController
  layout "application_admin"
  before_filter :authenticate_user!  
end

app/controllers/web/admin/images_controller.rb
class Web::Admin::ImagesController < Web::Admin::ApplicationController
  def index
    @images = Image.all    
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(params[:image])
    if @image.save
      redirect_to admin_images_path, notice: 'Image was successfully created.'
    else
      render action: "new" 
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])

    if @image.update_attributes(params[:image])
      redirect_to admin_images_path, notice: 'Album was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to admin_images_url 
  end
end

app/controllers/web/admin/welcome_controller.rb
class Web::Admin::WelcomeController < Web::Admin::ApplicationController
  def index
    @images = Image.limit 10
    @albums = Album.limit 10
  end
end

app/controllers/web/albums_controller.rb
class Web::AlbumsController < Web::ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @albums = Album.all
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include AuthHelper
  

  helper_method :current_user
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web/admin/albums_helper.rb
module Web::Admin::AlbumsHelper
  def albums_options
    options = []
    Album.all.each do |i|
      options << [i.title, i.id]
    end
    options
  end
end

app/helpers/web/admin/image_helper.rb
module Web::Admin::ImageHelper
end

app/helpers/web/admin/welcome_helper.rb
module Web::Admin::WelcomeHelper
end

app/helpers/web/albums_helper.rb
module Web::AlbumsHelper
end

app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
end

app/helpers/web/welcom_helper.rb
module Web::WelcomHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title PhotoArchive
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application" 
    = csrf_meta_tags
  body
    .container
      == yield 

app/views/layouts/application_admin.html.slim
doctype html
html
  head
    title PhotoArchive
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application" 
    = csrf_meta_tags
  body
    .container
      == yield 

app/views/web/admin/albums/_form.html.slim
= form_for @web_admin_album, url: admin_album_path(@web_admin_album) do |f|
  = render 'web/admin/application/error_messages', :errors => @web_admin_album.errors

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/web/admin/albums/edit.html.slim
h1 Editing web_admin_album

== render 'form'

= link_to 'Show', admin_album_path(@web_admin_album)
'|
= link_to 'Back', admin_albums_path

app/views/web/admin/albums/index.html.slim
h1 Listing web_admin_albums

table
  tr
    th Title
    th Description
    th State
    th
    th
    th

  - @web_admin_albums.each do |web_admin_album|
    tr
      td= web_admin_album.title
      td= web_admin_album.description
      td= web_admin_album.state
      td= link_to 'Show', admin_album_path(web_admin_album)
      td= link_to 'Edit', edit_admin_album_path(web_admin_album)
      td= link_to 'Destroy', admin_album_path(web_admin_album), :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Album', new_admin_album_path

app/views/web/admin/albums/new.html.slim
h1 New web_admin_album

== render 'form'

= link_to 'Back', admin_albums_path

app/views/web/admin/albums/show.html.slim
p#notice = notice

p
  b Title:
  = @web_admin_album.title
p
  b Description:
  = @web_admin_album.description
p
  b State:
  = @web_admin_album.state

= link_to 'Edit', edit_admin_album_path(@web_admin_album)
'|
= link_to 'Back', admin_albums_path

app/views/web/admin/application/_error_messages.html.slim
-if errors.any?
  .alert-message.block-message.error
    ul
      - errors.full_messages.each do |msg|
        li = msg

app/views/web/admin/images/_form.html.slim
= form_for @image, url: admin_image_path(@image) do |f|
  .field
    = f.label :album_id
    = f.select :album_id, albums_options  
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .image
    = image_tag @image.image_url(:small)
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/web/admin/images/edit.html.slim
h1 Web::Admin::Image#create

== render 'form'

app/views/web/admin/images/index.html.slim
h1 Web::Admin::Image#index

.images
  - @images.each do |image|
    div
      h4 = link_to image.title, edit_admin_image_path(image)
      p = image.description
      p = link_to image_tag(image.image_url(:small)), edit_admin_image_path(image)

app/views/web/admin/images/new.html.slim
h1 Web::Admin::Image#new

== render 'form'

app/views/web/admin/welcome/index.html.slim
.page-header
  h1 Web::Admin::Welcome#index

.row
  .span8
    ul
      - @images.each do |image|
        li = link_to image_tag(image.image_url(:small)), edit_admin_image_path(image)
  .span8
    ul
      - @albums.each do |album|
        li = link_to album.title, edit_admin_album_path(album)
      

app/views/web/albums/index.html.slim
h1 Web::Albums#index
p Find me in app/views/web/albums/index.html.slim

app/views/web/albums/show.html.slim
.page-header
  h1 Альбомы

.row
  .span16
    - @albums.each do |album|
      .album
        h3 = album.title
        ul
          - album.images.each do |image|
            = image_tag(image.image_url(:small))


    

app/views/web/users/new.html.slim
h1 Sign Up

= form_for @user do |f| 
  - if @user.errors.any?
    .error_messages
      h2 Form is invalid
      ul
        - for message in @user.errors.full_messages
          li = message
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password 
    = f.password_field :password 
  .field
    = f.label :password_confirmation 
    = f.password_field :password_confirmation 
  .actions 
    = f.submit 

app/views/web/welcome/index.html.slim
= current_user.inspect